<?php
/**
 * Created by PhpStorm.
 * User: юзер
 * Date: 09.11.2018
 * Time: 20:29
 */

require_once("./MagFunc.php");
require_once("./db.php");
require_once("./abstract.php");

class PageClass extends abstractPage
{
    private $BodyTopSalesHTML = "";
    private $BodyTopMenuHTML = "";
    private $BodyTopLogoHTML = "";

    function headHTML()
    {
        parent::headHTML(); // TODO: Change the autogenerated stub
        echo "<title>$this->Title</title>";
        echo file_get_contents("./skin/head-meta.txt");
        echo file_get_contents("./skin/head-link.txt");
    }

    function BodyTopHTML(){
        echo "        <nav class=\"colorlib-nav\" role=\"navigation\">
			<div class=\"top-menu\">
				<div class=\"container\">";
        echo $this->BodyTopLogoHTML;
        echo $this->BodyTopMenuHTML;
        echo "</div></div>";
        echo $this->BodyTopSalesHTML;
        echo "      </nav>";
    }

    function BodyBottomHTML(){
        echo file_get_contents("./skin/body-footer.txt");
    }

    function BodyContentHTML(){}

    function bodyHTML()
    {
        parent::bodyHTML(); // TODO: Change the autogenerated stub
        echo '<div class="colorlib-loader"></div><div id="page">';
        $this->BodyTopHTML();
        $this->MapMenu;
        $this->BodyContentHTML();
        $this->BodyBottomHTML();
        echo '</div>';
        echo file_get_contents("./skin/body-bottom-s.txt");
    }

    function SetTopLogo($SetsLogo,$SetsLogoLink = "/", $SetsLogoTitle = ""){
        $this->BodyTopLogoHTML="
        		 <div class=\"row\">
						<div class=\"col-sm-7 col-md-9\">
							<div id=\"colorlib-logo\"><a href=\"$SetsLogoLink\"".TitleToLink($SetsLogoTitle).">$SetsLogo</a></div>
						</div>
						<div class=\"col-sm-5 col-md-3\">
			            <form action=\"#\" class=\"search-wrap\">
			               <div class=\"form-group\">
			                  <input type=\"search\" class=\"form-control search\" placeholder=\"Search\">
			                  <button class=\"btn btn-primary submit-search text-center\" type=\"submit\"><i class=\"icon-search\"></i></button>
			               </div>
			            </form>
			         </div>
		         </div>";
    }

    function SetTopMenu($menu,$active="/"){
        $this->BodyTopMenuHTML="<div class=\"row\">
						<div class=\"col-sm-12 text-left menu-1\">
							<ul>\n";
        foreach ($menu as $item)
        {
            if($item['href']==$active) $ItemClass[]="active";
            if(isset($item['child']))
            {
                $ItemClass[]="has-dropdown";
                $subMenu="<ul class=\"dropdown\">\n";
                foreach ($item['child'] as $subItem)
                {
                    $subMenu.="<li><a href=\"".$subItem['href']."\"".TitleToLink($subItem['title']).">".$subItem['text']."</a></li>\n";
                }
                $subMenu.="</ul>";
            }
            if(isset($ItemClass)) $ItemClass=" class=\"".implode(" ",$ItemClass)."\""; else $ItemClass=NULL;
            $this->BodyTopMenuHTML.="<li$ItemClass><a href=\"".$item['href']."\" ".TitleToLink($item['title']).">".$item['text']."</a>$subMenu</li>\n";
            unset($ItemClass,$subMenu);
        }
        $this->BodyTopMenuHTML.="<li class=\"cart\"><a href=\"cart.html\"><i class=\"icon-shopping-cart\"></i> Cart [0]</a></li>\n</ul>\n
						</div>
					</div>";
    }

    function SetTopSale($sale)
    {
        if(is_array($sale)){
            $this->BodyTopSalesHTML='<div class="sale">
				<div class="container">
					<div class="row">
						<div class="col-sm-8 offset-sm-2 text-center">
							<div class="row">
								<div class="owl-carousel2">';
            foreach ($sale as $item)
            {
                $this->BodyTopSalesHTML.="<div class=\"item\">
										<div class=\"col\">
											<h3><a href=\"".$item['href']."\"".TitleToLink($item['title']).">".$item['text']."</a></h3>
										</div>
									</div>";
            }
            $this->BodyTopSalesHTML.='</div>
							</div>
						</div>
					</div>
				</div>
			</div>';}
    }
}
